### ISSUE TITLE
UI broken in macOS 14

### ISSUE THREAD

**Issue by iambenmitchell** [Jigsaw-Code/outline-apps#1653]
**Describe the bug**
Upon opening the outline app, the app is opened in the bottom right corner. Once you click the outline icon in the menu bar, the window pops up correctly, but buttons are not clickable

**To Reproduce**
1. Close outline
2. Open outline
3. notice that it opens in right corner
4. open in menu bar
5. notice nothing is clickable

**Expected behavior**
To be able to use outline fully.

**Screenshots**

**Client System (please complete the following information):**
 - Outline Client Version: 1.11.0
 - Your Operating System: macOS 14.0 Beta (23A5276g)

**Submit Feedback**
Please submit feedback through the app and label it with this issue number.

**Additional context**
This is a beta version of macOS.

**Comment by maddyhof** [comment]
We are in the process of upgrading the webview, which we expect will fix this issue on newer versions of macOS. Sorry for the inconvenience and thanks for bringing it to our attention.

**Comment by iambenmitchell** [comment]
> Sorry for the inconvenience and thanks for bringing it to our attention. 

No problem, I don’t expect any support and I do expect things to be broken when running an unreleased version of macOS. Just wanted to let you guys know :) 

Look forward to seeing an update and hopefully the app will run natively as it’s been running under Rosetta since m1 came out haha

**Comment by theoilside** [comment]
It was almost impossible to use official Outline Client on macOS 14, so I found alternative way to use Outline connection without Outline Client.
1. You can use any shadowsocks client. I prefer FoXray on macOS (it is available on iOS too).
2. Take your Outline key and look for everything after `ss://...` and before `/?outline=1`.
3. Part before `@ ` contains method and password. Decrypt this part with any Base64 decoder.
4. In my case after decryption it was `chacha20-ietf-poly1305:sJk5t08*****lbw9h7g`. The method is `chacha20-ietf-poly1305`, and the password is `sJk5t08*****lbw9h7g`.
5. After `@` look for the IP and port.
6. Add new Shadowsocks connection with info from steps 4-5. For transport I use `tcp`, every other option can be set as `none`.
Done!

**Comment by maddyhof** [comment]
Thanks for your patience! We're a small team, working as fast as we can. It's coming very soon!

**Comment by levinsondk** [comment]
As a temporary solution, worked for me:
1. Open VPN in System Settings
2. Switch on Outline
3. Close the "Please use the Outline app to connect" alert
4. Outline app interface should start working now.

**Comment by aikevinjobs** [comment]
> > As a temporary solution, worked for me on macOS 14.1 (23B74):
> > 
> > 1. Open VPN in System Settings
> > 2. Switch on Outline
> > 3. Close the "Please use the Outline app to connect" alert
> > 4. Outline app interface should start working now.
> 
> Better solution is to just hold CMD while trying to click buttons on the UI.
> 
> Seems to fix it.

very smart and flexible. simply solution. wonderful
