### ISSUE TITLE
I just want to use [OutlineAppleLib] to apple native project,and what the tunnelId should be when startvpn?

### ISSUE THREAD

**Issue by shadow-boy** [Jigsaw-Code/outline-apps#1802]
<img width="1047" alt="image" src="https://github.com/Jigsaw-Code/outline-client/assets/15226194/1cdee26e-8e03-4ab6-a590-1e3946a12e2b">

**Comment by shadow-boy** [comment]
How can i get the tunnelId?

**Comment by inkrot** [comment]
This ID is generated for each added tunnel. Initially created in frontend JS code using uuidv4 package

https://github.com/Jigsaw-Code/outline-client/blob/70d4b77488ca54da0dd7bd833d030e8eaf85cbc2/src/www/app/outline_server_repository/index.ts#L137

in swift code in might be like

```swift
let uuid = NSUUID().uuidString
```

**Comment by tahirmahm123** [comment]
Or if you want to use it in a native project you can simply refactor the code and remove tunnel id instances. I have done that. You will require to remove the tunnelId from PacketTunnelProvider.m as well.

**Comment by shadow-boy** [comment]
> Or if you want to use it in a native project you can simply refactor the code and remove tunnel id instances. I have done that. You will require to remove the tunnelId from PacketTunnelProvider.m as well.

YES,and I have done for this.

**Comment by shadow-boy** [comment]
https://github.com/Jigsaw-Code/outline-apps/issues/1802#issuecomment-1968852803
good solution for ios native project
