### ISSUE TITLE
Outline Manager for macOS' icon is outdated

### ISSUE THREAD

**Issue by thdrmrphy** [Jigsaw-Code/outline-apps#1851]
I made a fixed `.icns` file. I'm pretty sure it's sufficient to solve the problem and achieve icon parity on macOS Big Sur and above.
[Icon.icns.zip](https://github.com/Jigsaw-Code/outline-server/files/13327104/Icon.icns.zip)

**Comment by sbruens** [comment]
Deduping against #1911
