### ISSUE TITLE
Unable to run Outline-Manager 1.15.1 on MacOS Sonoma

### ISSUE THREAD

**Issue by sashmarin** [Jigsaw-Code/outline-apps#1855]
MacOS Sonoma 14.0 (on MacBook with M2 CPU) does not allow Outline-Manager 1.15.1 to run. The application is blocked with the message that Apple can't check if it is safe, "please contact the developers to update the application".

**Comment by CostaWebin** [comment]
New issue: empty white window on macOS Sequoia with 1.15.2 version.  App crashes.

**Comment by maddyhof** [comment]
@CostaWebin please open a new issue for this problem. Thank you!

**Comment by specOper99** [comment]
I know it is too late but somebody might need it one day
`sudo xattr -c -r ./Outline\ Manager.app`
