### ISSUE TITLE
Outline Manager using base 10 instead of base 2 to calculate data usage

### ISSUE THREAD

**Issue by maximumpxy** [Jigsaw-Code/outline-apps#1880]
**Describe the bug**
On the Outline Manager dashboard, the displayed used data and data limits in **GB** are calculated based on `totalBytes / (1000*1000*1000)` and not the proper conversion of `totalBytes / (1024*1024*1024)` . 

As a result, if an access key has an data limit of an actual 100GB, or `100 * (1024 * 1024 * 1024) = 107,374,182,400 bytes` and is updated through Outline API,  on the dashboard, its data limit mistakenly is shown as **107.37 GB**, because it uses this conversion: `107,374,182,400 / (1000 * 1000 * 1000)`

**To Reproduce**

- Create an access key by using the Outline API using libraries, such as: [https://github.com/jadolg/outline-vpn-api](outline-vpn-api), and add a data limit:

```
from outline_vpn.outline_vpn import OutlineVPN
Outline_API_URL = "<OutlineAPIKey>"
client = OutlineVPN(api_url=Outline_API_URL)
accessKeyName = input("Enter the name of the Access Key: ")
quota_to_increase = int(input("Enter the amount of GB you want to assign to this Access Key: "))
new_key = client.create_key(key_name=accessKeyName) #create Access Key
assert client.add_data_limit(new_key.key_id, quota_to_increase * (1024 * 1024 * 1024)) #Assign Quota in Bytes
```

- Now, close the Outline Manager, re-open, and check the dashboard again. The access key has the wrong displayed data limit, calculated based on `<quota_to_increase> / (1000 * 1000 * 1000)`.

Similarly, as a result of this wrong conversion, the access keys created directly from Outline Manager, and not the API, are assigned with wrong bytes in their data limits too. 
For instance, an access key that was decided to have 100 GB of data limit, is now have an actual 93 GB of data limit or: 

`100 * (1000 * 1000 * 1000) = 100,000,000,000 bytes / (1024 * 1024 * 1024 ) = 93.13 GB`

**Expected behavior**
To display the correct conversion of data in GB in the Outline Manager Dashboard.

**Screenshots**
<img width="716" alt="Outline Manager Issue in Converting Bytes to GigaBytes" src="https://user-images.githubusercontent.com/123524237/223405258-6d48ef46-19fa-4876-b436-df993dde5414.png">

**Client System (please complete the following information):**
 - Outline Manager on Windows

**Submit Feedback**
N/A

**Additional context**
None

**Comment by rorosin** [comment]
Will this be fixed?

**Comment by fortuna** [comment]
The use of the decimal system is the preferred way to interpret GB. See https://en.m.wikipedia.org/wiki/Byte#Multiple-byte_units.

The unit you are asking for is Gibibyte (GiB). We do not intend to use that. This is working as intended. Perhaps we can clarify it somewhere.
