### ISSUE TITLE
Wrong icon size on macOS Big Sur

### ISSUE THREAD

**Issue by kidonng** [Jigsaw-Code/outline-apps#1911]
The size is too large compared to native apps (Finder) or 3rd-party apps (iTerm):

![image](https://user-images.githubusercontent.com/44045911/112708900-f85b6800-8eef-11eb-896c-d2f38523871f.png)

**Comment by sbruens** [comment]
https://github.com/Jigsaw-Code/outline-apps/issues/1851#issue-2154542588 has example icons
