### ISSUE TITLE
Failed to install OpenVPN TAP Device Driver

### ISSUE THREAD

**Issue by g-struchin** [Jigsaw-Code/outline-apps#1986]
### Application

Outline Client

### Describe the bug

when installing "outline" (with administrator rights):
```
--------------------------- Установка Outline --------------------------- Sorry, we could not configure your system to connect to Outline. Please try running the installer again. If you still cannot install Outline, please get in touch with us and let us know that the TAP device failed to install with error code 1. --------------------------- ОК ---------------------------
```
when I run "add_tap_device.bat" (with administrator rights):
```
PS C:\Program Files (x86)\Outline> .\add_tap_device.bat
Интерфейс с таким именем не зарегистрирован на маршрутизаторе.

Creating TAP network device...
Device node created. Install is complete when drivers are installed...
Updating drivers for tap0901 from C:\Program Files (x86)\Outline\tap-windows6\OemVista.inf.
UpdateDriverForPlugAndPlayDevices failed, GetLastError=-536870325
tapinstall failed.
Could not create TAP network device.
```

### Steps to reproduce

1.  installing "outline" (with administrator rights):

### What did you expect to happen?

working client

### What actually happened?

the client won't let me connect to the server

### Outline Version

1.13.0.0

### What operation system are you using?

Windows

### Operating System Version

Windows 11 Pro 23H2 22631.3447

**Comment by g-struchin** [comment]
I downloaded the previous build from the site, now I downloaded 1.10.1.0 from Git, it installs the TAP driver without problems

**Comment by jyyi1** [comment]
This is caused by the OpenVPN tap device driver installation. We're hoping to find a way to avoid needing this driver in the future.

**Comment by jyyi1** [comment]
Duplicated with #1103 .
