### ISSUE TITLE
add ARM platfrom and CLI 

### ISSUE THREAD

**Issue by MrSteelRat** [Jigsaw-Code/outline-apps#2029]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Application

Outline Client

### What are you trying to do? What is your use case?

Hello, I would like to see in the near future a CLI version for the arm platform, in particular RassberyPI. Thank you for your work!!!

### Is your feature request related to a problem? Please describe it.

I need it for my home server to bypass blocking.

### Describe the solution you'd like.

Add, the need to work under the Arm platform with a CLI interface

### Describe alternatives you've considered

Didn't find a suitable one

**Comment by sbruens** [comment]
Try out our prototype CLI and let us know if it works for you: https://github.com/Jigsaw-Code/outline-sdk/tree/main/x/examples/outline-cli
