### ISSUE TITLE
[Bug]: connected to server but app shows not connected

### ISSUE THREAD

**Issue by qiangweihewu** [Jigsaw-Code/outline-apps#2031]
### Application

Outline Client

### Describe the bug

After clicked **Connect**, it connected to the server but app still showed  **Connect** (which means not connected). After a while, it was still connected but in the app, still showing "Connect" not "Disconnect". Then click Connect, and a notification comes up saying: We will restart Outline, it may require Admin right, are you sure to continue?

### Steps to reproduce

1. Open the app
2. Click "Connect"
3. After a while, still connected but in the app, still showing "Connect " not "Disconnect"
4. Click Connect, then a notification comes up saying: We will restart Outline, it may require Admin right, are you sure to continue?

### What did you expect to happen?

Showing Connected and 

### Outline Version

1.13.1

### What operation system are you using?

Windows

### Operating System Version

windows 11

**Comment by sbruens** [comment]
How did you check that you were actually connected?
