### ISSUE TITLE
[Bug]: It seems that your access key is not valid. If this happens again, please contact the person who gave it to you.

### ISSUE THREAD

**Issue by 3Artem3** [Jigsaw-Code/outline-apps#2035]
### Application

Outline Client

### Describe the bug

I encountered a problem where the application, when trying to connect to my server, returns a strange error: "It seems that your access key is not valid. If this happens again, please contact the person who gave it to you."

However, being the network administrator, I know that the key is correct. And that on other devices everything works the first time. But the problem occurs only on one of my computers. I conclude that the problem is on the program side. And perhaps the VPN network interface was not installed correctly. If this was installed on the device OpenVPN GUI and WARP. But when they were removed, the problem did not go away.
![image](https://github.com/Jigsaw-Code/outline-apps/assets/51854300/6ddc906f-cb61-4354-9ef9-abd370ffe66b)

### Steps to reproduce

1. Open the application
2. Add a VPN network using a pre-issued key
3. Click on the connect button and see an error message

### What did you expect to happen?

Normal connection, like on the other two devices

### What actually happened?

Connection problem and inability to use VPN

### Outline Version

1.13.1 (476278)

### What operation system are you using?

Windows

### Operating System Version

Windows 10

### Screenshots and Videos

![image](https://github.com/Jigsaw-Code/outline-apps/assets/51854300/21c2c243-e0c7-48bf-8525-23aaa4a2bf85)

**Comment by 3Artem3** [comment]
Just tried using `https://github.com/shadowsocks/shadowsocks-windows` and everything works great. The problem comes out in the application

**Comment by sbruens** [comment]
We need more information to diagnose the issue. Are you able to launch the Outline client in a terminal with `OUTLINE_DEBUG="true"` environment variable and share the log output with us? That would help us see what's going on.

**Comment by sbruens** [comment]
Closing this as we haven't heard back. Feel free to re-open in future if you have more details to share.
