### ISSUE TITLE
[Bug]: outline connected but still using ISP's DNS server

### ISSUE THREAD

**Issue by R1B0H** [Jigsaw-Code/outline-apps#2042]
### Application

Outline Client

### Describe the bug

outline client for Windows version 1.13.1.
I installed outline on my VPS with Oracle, and I installed client apps on my Android phone and Windows 10 PC. It connects from both Android and Windows. However with Windows, ipleak.net shows both my ISP (located in China) and my VPS's DNS server, with my ISP's DNS server at the first place. As a result I am not able to access Google Duckduckgo etc. With the Android device, outline VPN works totally fine.

### Steps to reproduce

1 install server and client(v1.13.1)
2 connect from China by its ISP
3 Visit ipleak.net to check DNS servers

### Outline Version

1.13.1

### What operation system are you using?

Windows

**Comment by sbruens** [comment]
We haven't been able to reproduce this. Could you share more details, so we can further debug?

**Comment by R1B0H** [comment]
Then it may have to do with my browser settings.
When I have confirmation will let you know with more details.
Thanks!


     On Thursday, July 4, 2024 at 04:11:04 AM GMT+8, Sander Bruens ***@***.***> wrote:  
 
 


We haven't been able to reproduce this. Could you share more details, so we can further debug?
