### ISSUE TITLE
[Bug]: Cannot find connected.png tray icon image

### ISSUE THREAD

**Issue by timehollyname** [Jigsaw-Code/outline-apps#2047]
### Application

Outline Client

### Describe the bug

The application is not started with the command "npm run action client/electron/start windows". Cannot find connected.png tray icon image.

### Steps to reproduce

1. npm run action client/electron/start windows

### Outline Version

latest

### What operation system are you using?

Windows

### Operating System Version

Windows 11 x64

### Screenshots and Videos

![image](https://github.com/Jigsaw-Code/outline-apps/assets/72518011/21e6a809-f222-4d07-b4e5-02b012a68a2a)
![image](https://github.com/Jigsaw-Code/outline-apps/assets/72518011/2acc5f97-6c55-4089-9625-60de963b94ea)
![image](https://github.com/Jigsaw-Code/outline-apps/assets/72518011/1a94948f-9e55-4269-a60c-1ed5e9cfc9e3)

**Comment by sbruens** [comment]
This is a known issue. Please see #2015 for more details and temporary workaround.

Dupe #2015
