### ISSUE TITLE
[Bug]: If the internet is interrupted, the connection cannot be closed.

### ISSUE THREAD

**Issue by Phoenix1112** [Jigsaw-Code/outline-apps#2098]
### Application

Outline Client

### Describe the bug

İ am using android samsung s21 fe. I turn on VPN when connected to home internet.Recently, there was an internet outage in the home internet due to a problem with the internet service provider. I'm trying to disconnect outline vpn on the phone but it doesn't work. Even though I turn on and off the wifi and airplane mode on the phone, this time I cannot connect to the home internet. This is because Outline VPN not successfully shuts down itself when the internet goes out.

I solved this problem as follows.

settings > applications > outline > force stop

### Steps to reproduce

Connect to home internet and activate VPN on your Android phone.

Disconnect your internet connection from your modem and turn it back on after a few minutes.

Connect to WiFi again, but you will not be able to open any pages from the web browser.

Trying to disconnect from outline but that won't work.

### Outline Version

1.12.2

### What operation system are you using?

Android

**Comment by sbruens** [comment]
We have been unable to reproduce this on Version 1.13. @Phoenix1112 are you able to update the app and see if it still occurs?
