### ISSUE TITLE
[Bug]: Home page not accessible from Crimea

### ISSUE THREAD

**Issue by ProfaneServitor** [Jigsaw-Code/outline-apps#2187]
### Application

Outline Client

### Describe the bug

When you try to visit https://getoutline.org/ from Crimea, the page doesn't load. I don't see a message stating that it is blocked by Roskomnadzor, so it's probably caused by faulty CDN.

### Steps to reproduce

1. Connect to Crimean VPN
2. Go to https://getoutline.org/ 

### Outline Version

1.12.2

### What operation system are you using?

Linux

### Screenshots and Videos

[![Screenshot-from-2024-08-29-20-07-33.png](https://i.postimg.cc/c1RYxj3W/Screenshot-from-2024-08-29-20-07-33.png)](https://postimg.cc/2353T0T9)

**Comment by sbruens** [comment]
[Bookmark this mirrored site](https://s3.amazonaws.com/outline-vpn/index.html) to use if you cannot access [getoutline.org](http://getoutline.org/).
