### ISSUE TITLE
[Bug]: Endless "Outline has been successfully initialized, please try again to connect to the server" Windows 10

### ISSUE THREAD

**Issue by jzr-supove** [Jigsaw-Code/outline-apps#2207]
### Application

Outline Client

### Describe the bug

When I try to connect to a server, I get a message 

> We will initialize Outline, which may require admin permissions. Would you like to proceed?

I press Ok, black screen appears asking me to allow to execute some cmd command, I allow. Black screen disappears, IU starts to display

> Initializing Outline...,

then after few seconds it changes to 

> Outline has been successfully initialized, please try again to connect to the server.

When I press "Connect" again, the same exact process repeats. So I cannot actually connect to a server, it seems that I am just endlessly initializing Outline.

### Steps to reproduce

1. Download Outline Client for Windows from official [site](https://getoutline.org/get-started/#step-3) with this [download link](https://s3.amazonaws.com/outline-releases/client/windows/stable/Outline-Client.exe)
2. Install and add server
3. Press "Connect"
4. Window pops up saying "We will initialize Outline, which may require admin permissions. Would you like to proceed?". Press "Ok"
5. This prompt pops up, press "Yes":
    ![image](https://github.com/user-attachments/assets/ccbe903b-4f5e-4597-b54c-87c758c0e325)
7. It says "Initializing Outline", then says this:
    ![image](https://github.com/user-attachments/assets/15ced8be-544e-45dd-9825-963178a2fc76)
8. Repeat from step 3

### What did you expect to happen?

Successfully connects to the server

### What actually happened?

Cannot connect to the server

### Outline Version

Version 1.13.1 (476278)

### What operation system are you using?

Windows

### Operating System Version

Version 10.0.19045 Build 19045

### Screenshots and Videos

https://github.com/user-attachments/assets/971318f3-38fe-4286-a8d1-025c0ed947a7

**Comment by jzr-supove** [comment]
Related: https://github.com/Jigsaw-Code/outline-apps/issues/2052

**Comment by sbruens** [comment]
Thank you for reaching out! Please contact us through the application on the device where you’re experiencing this issue  – or at [support.getoutline.org](https://support.getoutline.org/) – and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org](https://support.getoutline.org/s/) for access to help articles and more.

**Comment by jzr-supove** [comment]
@sbruens 
Indded I tried contacting through the [support.getoutline.org](https://support.getoutline.org/) but it didn't let me to, whith this template response:

![image](https://github.com/user-attachments/assets/65069197-e13f-40c1-8f7b-d2f0686b8ba3)

**Comment by jzr-supove** [comment]
Aight, I should have selected the latest option "General feedback" to bypass this template response. I've opened the ticket, it says:

> Thanks for helping us improve! We love hearing from you. You can find your ticket reference number in the confirmation email. 

Now, waiting for the confirmation email...

**Comment by sbruens** [comment]
Also check out #1451 for some useful tips to help you troubleshoot.
