### ISSUE TITLE
[Bug]: The Linux client asks for sudo permission in fedora 40

### ISSUE THREAD

**Issue by abnerkaizer** [Jigsaw-Code/outline-apps#2213]
### Application

Outline Client

### Describe the bug

The Linux client asks for sudo permission in fedora 40, but after giving it, it says that it wasn't possible to initialize the application. 
I'm using the same server in the Windows client just fine.

### Steps to reproduce

1. Open the application.
2. Try to connect to server.
3. Give sudo permit.
4. Fail.

### Outline Version

1.13.1 (476278)

### What operation system are you using?

Linux

### Operating System Version

Fedora 40

### Screenshots and Videos

![Captura de tela de 2024-09-18 19-23-02](https://github.com/user-attachments/assets/d8717929-2ada-442b-9afd-fc44699a1a4b)
![Captura de tela de 2024-09-18 19-28-43](https://github.com/user-attachments/assets/f13811ab-0d5e-432a-9197-2dd1c71fc5bf)

**Comment by sbruens** [comment]
Unfortunately, we don't support Fedora. If you figure it out, please feel free to share your solution here for future readers.
