### ISSUE TITLE
Outline Manager binary on the releases page

### ISSUE THREAD

**Issue by ClusterM** [Jigsaw-Code/outline-apps#2216]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Application

Outline Manager

### What are you trying to do? What is your use case?

I'm trying to download Outline Manager in a country where getoutline.org is blocked. But there are only client binaries on the [releases page](https://github.com/Jigsaw-Code/outline-apps/releases).

### Describe the solution you'd like.

Please upload Outline-Manager.exe to releases too.

**Comment by sbruens** [comment]
Check out our official mirrors listed at https://github.com/Jigsaw-Code/outline-releases.

**Comment by ClusterM** [comment]
Thank you!

**Comment by Korb** [comment]
@sbruens, where on your site can I see the version change history and which version is currently available for download?

**Comment by sbruens** [comment]
@Korb We don't currently publish release updates to our website.

The way to get the version change history is to reference the GitHub tags for our app releases https://github.com/Jigsaw-Code/outline-apps/tags. For example, the tags show that the latest Manager Linux release is 1.16.0 and you can use that release tag to get the change history with the previous release for that platform 1.15.2: https://github.com/Jigsaw-Code/outline-apps/compare/manager_linux/v1.15.2...manager_linux/v1.16.0

**Comment by Korb** [comment]
Isn't this a link to an updated release of Outline client app? –

![Image](https://github.com/user-attachments/assets/5b517b10-5587-465d-82aa-fbd34399eaf3)

**Comment by sbruens** [comment]
@Korb Yes, that gets you the latest version. You asked if there's a way you can see the version change history or which version that is, which we don't have on that website. We just link to the latest binaries there. You'd have to open the downloaded app to see the version.
