### ISSUE TITLE
[Bug]: Error while installing Outline Client

### ISSUE THREAD

**Issue by lll-Death-lll** [Jigsaw-Code/outline-apps#2219]
### Application

Outline Client

### Describe the bug

Error while installing Outline Client/after installation on Windows 10

### Steps to reproduce

1. Open the installer
2. Wait for installation to finish
3. Open the app
4. Connect to any server

### What did you expect to happen?

Outline Client installs without errors and after start will connect to server

### What actually happened?

Installation ends with an error
![image](https://github.com/user-attachments/assets/1de61fde-7aa8-48e7-831b-3c94b8fc474d)

Connection in the app to any server doesn't work
![image](https://github.com/user-attachments/assets/8f663fca-f0c3-4925-a8ef-f852a82dda6a)

### Outline Version

1.13.1 (476278)

### What operation system are you using?

Windows

### Operating System Version

Windows 10 22H2

**Comment by Bideldy** [comment]
Всем привет. Что делать если код ошибки 1. Ноутбук - Windows 10

**Comment by sbruens** [comment]
Can you follow the steps suggested in https://github.com/Jigsaw-Code/outline-apps/issues/1451#issuecomment-1289417567 and confirm which components failed to install?

**Comment by lll-Death-lll** [comment]
> Can you follow the steps suggested in [#1451 (comment)](https://github.com/Jigsaw-Code/outline-apps/issues/1451#issuecomment-1289417567) and confirm which components failed to install?

Service installed, tap install failed,
![image](https://github.com/user-attachments/assets/580c9a01-a590-46ae-ac89-e048f5e98301)
![image](https://github.com/user-attachments/assets/e0355a19-d127-4615-b00f-6346dc20e258)

**Comment by jyyi1** [comment]
Thanks @lll-Death-lll for the information. Could you please just manually rename your newly installed OpenVPN TAP device to "outline-tap0"? It seems we are trying to rename the wrong device "Ethernet 2".

**Comment by lll-Death-lll** [comment]
I solved the problem by resetting the network settings and then reinstalling
