### ISSUE TITLE
[Bug]: Outline Manager can't create a GCP project

### ISSUE THREAD

**Issue by ayy-em** [Jigsaw-Code/outline-apps#2238]
### Application

Outline Manager

### Describe the bug

While setting up your VPN via Google Cloud, it successfully authorizes, but even when granted all requested permissions, upon filling in the project name and selecting an active billing account, you get "An error occurred while setting up your Google Cloud project" instead

### Steps to reproduce

1. Open Outline Manager on PC
2. Select "Google Cloud Project"
3. Authorize using an account that has admin rights on GCP
4. Fill in the project name and select a billing account, then click `Create Project`

### What did you expect to happen?

GCP Project is created, setup continues

### What actually happened?

`An error occurred while setting up your Google Cloud project` error modal, no further actions/interactions

### Outline Version

1.15.2

### What operation system are you using?

Windows

### Operating System Version

Win10

**Comment by DanyaBrain** [comment]
ah my google cloud account ran out of projects with billing enabled. I turned off billing for a few projects and everything started working properly

**Comment by sbruens** [comment]
Sounds like you were able to resolve your issue. Feel free to re-open if there's some action required from us. Thanks!

**Comment by ayy-em** [comment]
@sbruens the guy is not the OP, I am, and itr did not get resolved for me heh

**Comment by yvesloy** [comment]
> ah my google cloud account ran out of projects with billing enabled. I turned off billing for a few projects and everything started working properly

This solved the issue for me.
