### ISSUE TITLE
[Bug]: Client cannot start VPN on Archlinux OS.

### ISSUE THREAD

**Issue by sudoPrey** [Jigsaw-Code/outline-apps#2239]
### Application

Outline Client

### Describe the bug

I download via ./Downloads/Outline-Client.AppImage, having first run chmod u+x ./Downloads/Outline-Client.AppImage, the application. After that I try to start VPN, the application asks me for a password, I enter it, and I get an error 'Failed to launch Outline. Send feedback through the app.'.

# System Details Report
---
## Report details
- **Date generated:**                              2024-10-10 09:58:06
## Hardware Information:
- **Hardware Model:**                              ASUS ROG STRIX Z790-A GAMING WIFI
- **Memory:**                                      32.0 GiB
- **Processor:**                                   13th Gen Intel® Core™ i9-13900K × 32
- **Graphics:**                                    NVIDIA GeForce RTX™ 4060 Ti
- **Disk Capacity:**                               1.6 TB
## Software Information:
- **Firmware Version:**                            2503
- **OS Name:**                                     Arch Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.2-arch1-1
- 
I use NetworkManager.

### Steps to reproduce

1. Open the Application
2. Try running a VPN
3. Enter the root password
4. Failed to launch Outline. Send feedback through the app

### What did you expect to happen?

That the VPN will start normally and everything will be fine.

### What actually happened?

[log.txt](https://github.com/user-attachments/files/17323633/log.txt)

### Outline Version

1.13.1 (476278)

### What operation system are you using?

Linux

### Operating System Version

Operating System: Arch Linux Kernel: Linux 6.11.2-arch1-1

### Screenshots and Videos

Outline is starting
loading web app from file:///tmp/.mount_OutlinSnljkr/resources/app.asar/client/www/index_electron.html?appName=Outline
Could not load active tunnel:  [Error: ENOENT: no such file or directory, open '/home/Prey/.config/Outline/connection_store'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/Prey/.config/Outline/connection_store'
}
Checking for update
MESA-LOADER: failed to retrieve device information
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Update for version 1.13.1 is not available (latest version: 1.13.1, downgrade is disallowed).
connecting to 469f0226-a1d8-4ad0-8638-960b11cffc54...
using tun2socks to check connectivity
[EXIT - tun2socks]: Exited with code 0
UDP support: true
starting routing daemon
Routing daemon socket setup failed Error: connect ENOENT /var/run/outline_controller
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/outline_controller'
}
could not connect: G (routing daemon is not running)
[EXIT - tun2socks]: Exited with code 12
could not stop tun2socks: Process terminated by non-zero exit code: 12
tun2socks terminated due to Error: Process terminated by non-zero exit code: 12
disconnected from 469f0226-a1d8-4ad0-8638-960b11cffc54
installing outline routing service...
copying service installation files to /tmp/pG8GGy
all service installation files copied to /tmp/pG8GGy successfully
trying to run command as root:  trap "/usr/bin/chattr -R -i /tmp/pG8GGy" EXIT; /usr/bin/chattr -R +i /tmp/pG8GGy && /usr/bin/echo "e0644a3750b6c770e4f2f2e2e7de0de1e46386eed733d7841f35d9e4aa53c1cd  /tmp/pG8GGy/install_linux_service.sh" | /usr/bin/shasum -a 256 -c && /usr/bin/echo "0a2d2b874d4d200145b1e3a7cc5818fb27e5c0ed69ebb4f4057e066e0b7fdc4a  /tmp/pG8GGy/OutlineProxyController" | /usr/bin/shasum -a 256 -c && /usr/bin/echo "8bfab08036441bcbb558927bdecd97eebf8c2d365a2a7fdb6c0032c2afc965a2  /tmp/pG8GGy/outline_proxy_controller.service" | /usr/bin/shasum -a 256 -c && "/tmp/pG8GGy/install_linux_service.sh" "Prey"

/bin/bash: строка 1: /usr/bin/shasum: Это каталог
/usr/bin/echo: ошибка записи: Обрыв канала

command is running as root but failed:  Error: Command failed: cd "/home/Prey"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; trap \"/usr/bin/chattr -R -i /tmp/pG8GGy\" EXIT; /usr/bin/chattr -R +i /tmp/pG8GGy && /usr/bin/echo \"e0644a3750b6c770e4f2f2e2e7de0de1e46386eed733d7841f35d9e4aa53c1cd  /tmp/pG8GGy/install_linux_service.sh\" | /usr/bin/shasum -a 256 -c && /usr/bin/echo \"0a2d2b874d4d200145b1e3a7cc5818fb27e5c0ed69ebb4f4057e066e0b7fdc4a  /tmp/pG8GGy/OutlineProxyController\" | /usr/bin/shasum -a 256 -c && /usr/bin/echo \"8bfab08036441bcbb558927bdecd97eebf8c2d365a2a7fdb6c0032c2afc965a2  /tmp/pG8GGy/outline_proxy_controller.service\" | /usr/bin/shasum -a 256 -c && \"/tmp/pG8GGy/install_linux_service.sh\" \"Prey\""
/bin/bash: строка 1: /usr/bin/shasum: Это каталог
/usr/bin/echo: ошибка записи: Обрыв канала

    at ChildProcess.exithandler (node:child_process:408:12)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at Pipe.<anonymous> (node:net:687:12) {
  killed: false,
  code: 126,
  signal: null,
  cmd: 'cd "/home/Prey"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; trap \\"/usr/bin/chattr -R -i /tmp/pG8GGy\\" EXIT; /usr/bin/chattr -R +i /tmp/pG8GGy && /usr/bin/echo \\"e0644a3750b6c770e4f2f2e2e7de0de1e46386eed733d7841f35d9e4aa53c1cd  /tmp/pG8GGy/install_linux_service.sh\\" | /usr/bin/shasum -a 256 -c && /usr/bin/echo \\"0a2d2b874d4d200145b1e3a7cc5818fb27e5c0ed69ebb4f4057e066e0b7fdc4a  /tmp/pG8GGy/OutlineProxyController\\" | /usr/bin/shasum -a 256 -c && /usr/bin/echo \\"8bfab08036441bcbb558927bdecd97eebf8c2d365a2a7fdb6c0032c2afc965a2  /tmp/pG8GGy/outline_proxy_controller.service\\" | /usr/bin/shasum -a 256 -c && \\"/tmp/pG8GGy/install_linux_service.sh\\" \\"Prey\\""'

**Comment by sudoPrey** [comment]
it looks like I was able to fix this error by reinstalling base-devel and coreutils.

sudo pacman -S — needed base-devel, sudo pacman -S coreutils.

In addition, I decided to use git and make the package myself via makepkg -si.

**Comment by sbruens** [comment]
Glad you were able to get it to work. For reference, we are tracking Arch Linux support in #1685.
