### ISSUE TITLE
[Bug]: Transparent 'Add server' button in MacOS app

### ISSUE THREAD

**Issue by chiliec** [Jigsaw-Code/outline-apps#2277]
### Application

Outline Client

### Describe the bug

Transparent 'Add server' button in `Access key detected` window.

### Steps to reproduce

1. Click Plus button
2. Paste valid access key
3. Transparent 'Add server' button

### What did you expect to happen?

Usual 'Add server' button

### What actually happened?

'Add server' transparent button

### Outline Version

1.12.1 (474739)

### What operation system are you using?

macOS

### Operating System Version

Sequoia 15.1 (24B83)

### Screenshots and Videos

<img width="412" alt="Screenshot 2024-11-18 at 1 30 24 PM" src="https://github.com/user-attachments/assets/4a1ac872-e146-4c81-a1c4-f377e5388501">

**Comment by fortuna** [comment]
Try using the latest version. We have released 1.13 and 1.14

**Comment by chiliec** [comment]
Thanks!
