### ISSUE TITLE
[Bug]: UI problem and doesn't respond in MacOS Catalina 10.15.7 with 1.14.0

### ISSUE THREAD

**Issue by leoneuro** [Jigsaw-Code/outline-apps#2283]
### Application

Outline Client

### Describe the bug

After update to 1.14.0 on MacOS Catalina 10.15.7 the UI is corrupt, the app doesn't work and doesn't respond.

### Steps to reproduce

1. Update the app (or install from Mac App Store)
2. Launch
3. Doesn't respond

### Outline Version

1.14.0

### What operation system are you using?

macOS

### Operating System Version

Catalina 10.15.7

### Screenshots and Videos

![bug_outline](https://github.com/user-attachments/assets/1caa8e71-3e8c-4461-9b4b-c770d9ef7e97)

**Comment by sfactor** [comment]
Same here. 

macOS 11.7.10

Outline client version 11.4.0 from App Store
![Uploading IMG_5435.jpeg…]()

**Comment by m99vpy** [comment]
Same for me: MacOS BigSur 11.7, Outline client 1.14.0
<img width="330" alt="Снимок экрана 2024-11-21 в 19 24 49" src="https://github.com/user-attachments/assets/ecc5b0fa-6cf1-4d0b-8252-a500889cf336">

**Comment by websoda** [comment]
Same here.

macOS **Catalina 10.15.7**
**Outline 1.14.0** from AppStore

![image](https://github.com/user-attachments/assets/87422fdb-a65a-463f-873b-5f87d297bcee)

**Comment by cyrexskywalker** [comment]
did u solve this problem? i have the same

> Same for me: MacOS BigSur 11.7, Outline client 1.14.0 <img alt="Снимок экрана 2024-11-21 в 19 24 49" width="330" src="https://private-user-images.githubusercontent.com/1190033/388693490-ecc5b0fa-6cf1-4d0b-8252-a500889cf336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NzM5MDEsIm5iZiI6MTczMjU3MzYwMSwicGF0aCI6Ii8xMTkwMDMzLzM4ODY5MzQ5MC1lY2M1YjBmYS02Y2YxLTRkMGItODI1Mi1hNTAwODg5Y2YzMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMjIyNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWMwZThmMTZjZWIzNTM0NTEzNWRhZGIyNTExNzY1NmEzZTI0NGI0NGFmMmM2YjZmNjVjNGQ2OGM4MTA3ODcwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.44t9z8gHKl79hwT2dR4xf06nqoWFJFba3ZDdaHIff9Q">

**Comment by sbruens** [comment]
We are aware of the issue with the new release and working on getting a fix out as soon as we can. #2278 has been merged and a new build is currently going through the release process.

For posterity, this issue is the same as the one affecting iOS (#2276) and is a problem specifically with older versions of Safari (<16.4). If you're able to upgrade to a newer version of Safari, you can get unblocked sooner.

**Comment by screwgoth** [comment]
> We are aware of the issue with the new release and working on getting a fix out as soon as we can. #2278 has been merged and a new build is currently going through the release process.
> 
> For posterity, this issue is the same as the one affecting iOS (#2276) and is a problem specifically with older versions of Safari (<16.4). If you're able to upgrade to a newer version of Safari, you can get unblocked sooner.

When is the fix expected to Release ?

**Comment by itjinshan** [comment]
Could we please get some updates on this issue? When should we expect a new release to patch this bug? Thanks guys!

**Comment by q1LLa** [comment]
The same problem. How soon will the update be released?

![image](https://github.com/user-attachments/assets/83775ca6-5f58-458f-a73e-43ad0331beae)
![image](https://github.com/user-attachments/assets/10fad567-62d2-42a5-9b2c-692c94496148)

**Comment by itjinshan** [comment]
@sbruens I was able to update my safari to 16.x but still have this bug. Please share any other work arounds? I really need vpn on my ASAP, and this has been blocking me for too long. Thanks

**Comment by khantzawhein** [comment]
any update regarding this UI issue?

**Comment by sbruens** [comment]
We're working hard to get the new release out to you all as soon as possible. Unfortunately Apple does not have a way to rollback to a previous version, so to get an update out we need to do a full new release and go through the entire release process again, which involves several steps and can unfortunately take some time.

The good news is that the new build is already with our QA team, and then it's off to Apple for final approval. I'm hopeful we can get there by the end of the week (assuming we hit no snags), but know that the timing is slightly out of our control.

Thanks for your patience and understanding. We know this is frustrating.

PS: Thanks @itjinshan for the note that upgrading Safari does not reliably work on all platforms. I've amended my earlier comment to avoid confusion. Some folks found workarounds in #2285, but know that it involves using a download not verified or endorsed by Jigsaw.

**Comment by sbruens** [comment]
Just a quick update that the app is currently with Apple for final review.

**Comment by sbruens** [comment]
Hi everyone,

Thanks for your patience. Apple has accepted the app and we've just released **version 1.14.1** to address the reported issues. 

Apple is currently rolling out the update in [phases](https://developer.apple.com/help/app-store-connect/update-your-app/release-a-version-update-in-phases/), so it might not be immediately available for everyone. You can either wait for the automatic update or manually update to the latest version directly from the App Store: https://apps.apple.com/us/app/outline-app/id1356178125

If you continue to experience problems after updating, please let us know by re-opening this issue.

We appreciate your reports and feedback!
