### ISSUE TITLE
[Bug]: Outline Client Mac wont let me add a server

### ISSUE THREAD

**Issue by ersh0ff** [Jigsaw-Code/outline-apps#2285]
### Application

Outline Client

### Describe the bug

When you launch the application, a window opens with the text:

**Outline does not collect your personal data

In the event of an error or crash in the app, or if the server administrator has authorized the sending of anonymous server usage data, the recall will**

And below that, “OK.” When I click on “OK” nothing happens.
The app just doesn't respond to anything. This came up recently with a new version of the app.

### Steps to reproduce

1. I open the app
2. I'm clicking on “OK.”
3. The application is not responding and nothing is happening

### What did you expect to happen?

I was expecting a key to be added

### What actually happened?

Nothing

### Outline Version

1.14.0

### What operation system are you using?

macOS

### Operating System Version

Big Sur 11.7.10 (20G1427)

**Comment by ersh0ff** [comment]
**Here is an illustrative video of the error**

https://github.com/user-attachments/assets/104d0b78-75a5-464b-a6cd-1afaa87344c1

**Comment by ersh0ff** [comment]
Friends who have the same problem, download the dmg version: 
https://github.com/Jigsaw-Code/outline-apps/issues/1177#issuecomment-1188908966

**Comment by lepregnom** [comment]
The DMG version wasn't working, it was not been able to connect to the server. But!!! 
1) Delete the new version that's not adding server. 
2) Download the DMG version 
3) Add server, it wouldn't connect, but that's not what you need
4) Download the version from App Store
5) The server from the old version will automatic add to new one

**Comment by Blyabtroi** [comment]
Same bug, same Mac OS version, but I cant fix it by the previous message.

**Comment by sbruens** [comment]
Dupe #2283

**Comment by ersh0ff** [comment]
> Same bug, same Mac OS version, but I cant fix it by the previous message.

Have you tried uninstalling the app from the AppStore and downloading the DMG version? When I run DMG, I have two Outline hanging in my processes. Use “system monitoring” to terminate one of them and enjoy life.

**Comment by ersh0ff** [comment]
> Thank you for your comment. Yes, I've had two of them running, but DMG version can't connect (shows an error) and official version acts like yours from your video attachment.

Sometimes I have the exact same thing and have to restart my macbook, and run dmg again and terminate one of the two Outline processes again (if I don't do that I get an error too).

Very much looking forward to the official update!
