### ISSUE TITLE
Update Outline Client version in the `Releases` section

### ISSUE THREAD

**Issue by Korb** [Jigsaw-Code/outline-apps#2297]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Application

Outline Client

### What are you trying to do? What is your use case?

Go to https://github.com/Jigsaw-Code/outline-apps/releases/ and download the latest version of the application.

### Is your feature request related to a problem? Please describe it.

Only version **1.10.1** (2023-03-21) is available in Releases.

### Describe the solution you'd like.

Create a new release on Github after publishing the next version of the application on getoutline.org.

### Describe alternatives you've considered

Download Outline Client **1.12.1** (471860) [here](https://s3.amazonaws.com/outline-releases/client/windows/stable/Outline-Client.exe).

**Comment by jyyi1** [comment]
Hi @Korb , please just check out the links here: https://github.com/Jigsaw-Code/outline-releases

**Comment by Korb** [comment]
> please check out the links here

The link you provided leads to a page

> This repository has been archived by the owner on May 31, 2024. It is now read-only.

that contains the same link I provided in the first post. What exactly did you want to say with your message, please explain. That this repository is outdated and all issues should be placed in Jigsaw-Code' outline-releases? Or that the Outline Client for Windows RIP project will no longer be updated and alternative solutions should be sought?

**Comment by sbruens** [comment]
The [link](https://github.com/Jigsaw-Code/outline-releases) is our official list of where to find our official release channels. You should be able to download the latest releases from the links on that page and those are the same links as provided on our official website https://getoutline.org.

We no longer publish new releases on GitHub, but you can find them on 1 of the above links.

**Comment by sbruens** [comment]
I've just removed the "Releases" link on the repo's homepage, I realize that is probably confusing because we stopped publishing releases on GitHub. Hopefully that clears it up as the main repo README has links to download the applications.

**Comment by Korb** [comment]
Related question in discussions — https://github.com/Jigsaw-Code/outline-apps/discussions/2553

**Comment by Korb** [comment]
> Noted. We had an automated process that didn't work out, that's why we stopped doing this. We will look into adding this to our manual release process.

@daniellacosse, @sbruens, `getoutline.org` is currently blocked in Russia and is inaccessible without a VPN:

> Secure Connection Failed. An error occurred during a connection to getoutline.org.
> Error code: PR_CONNECT_RESET_ERROR
> The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> Please contact the website owners to inform them of this problem.

> This site can’t be reached
> The connection was reset.
> Try checking the connection
> [Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
> [Running Windows Network Diagnostics](javascript:diagnoseErrors())
> ERR_CONNECTION_RESET

GitHub isn't blocked yet. How can I download `Outline Client` without a cross-border VPN connection?

**Comment by ohnorobo** [comment]
@Korb are you able to access Amazon s3?
If so you can try downloading our official release binaries directly from the [s3 links here](https://github.com/Jigsaw-Code/outline-releases)
That does not require any connection to getoutline.org.

**Comment by Korb** [comment]
> you can try downloading our official release binaries directly from the s3 links here

@ohnorobo, great! Should I create an issue or PR to add this info to the `README.md` of the current repo?

**Comment by emohandesi** [comment]
@ohnorobo,
Does the S3 link get updated automatically or do you upload the Outline binary to it manually? Sometimes, I have seen the S3 link does not have the latest Outline version.

**Comment by Korb** [comment]
> the S3 link does not have the latest Outline version.

I see the opposite:

- F-Droid — 1.18.0-rc.1 (51) (2025-11-26)[^1]
- IzzyOnDroid — 1.18.0-rc.1 (2025-11-26)[^2]
- Google Play — 1.17.0 (2018-03-19)
- S3:
  - Android — 1.19.0 build 490239
  - Windows — 1.19.0.0 (2025-12-04)

[^1]: #1447, #1944
[^2]: #50
