### ISSUE TITLE
[Bug]: Cannot connect with outline in Windows 11: outline-ipc-start-proxying

### ISSUE THREAD

**Issue by alikhani97** [Jigsaw-Code/outline-apps#2301]
### Application

Outline Client

### Describe the bug

In windows 11 I'm getting this error when I want to connect:
ERR_INTERNAL_ERROR
Internal service error
Caused by:
Error: Error invoking remote method 'outline-ipc-start-proxying' Error

in outline trace log:

Sentry Logger [log]: Starting Electron crashReporter
Sentry Logger [log]: Integration installed: SentryMinidump
Sentry Logger [log]: Integration installed: ElectronBreadcrumbs
Sentry Logger [log]: Integration installed: Net
Sentry Logger [log]: Integration installed: MainContext
Sentry Logger [log]: Integration installed: ChildProcess
Sentry Logger [log]: Integration installed: OnUncaughtException
Sentry Logger [log]: Integration installed: PreloadInjection
Sentry Logger [log]: Integration installed: AdditionalContext
Sentry Logger [log]: Integration installed: Screenshots
Sentry Logger [log]: Integration installed: RendererProfiling
Sentry Logger [log]: Integration installed: InboundFilters
Sentry Logger [log]: Integration installed: FunctionToString
Sentry Logger [log]: Integration installed: LinkedErrors
Sentry Logger [log]: Integration installed: Console
Sentry Logger [log]: Integration installed: Http
Sentry Logger [log]: Integration installed: Undici
Sentry Logger [log]: Integration installed: OnUnhandledRejection
Sentry Logger [log]: Integration installed: ContextLines
Sentry Logger [log]: Integration installed: LocalVariablesSync
Sentry Logger [log]: Integration installed: Modules
Sentry Logger [log]: Integration installed: RequestData
Sentry Logger [log]: Integration installed: MainProcessSession
Sentry Logger [log]: The preload script could not be injected automatically. This is most likely caused by bundling of the main process
Outline is starting
loading web app from file:///C:/Program%20Files%20(x86)/Outline/resources/app.asar/client/www/index_electron.html?debug=true&appName=Outline
Could not load active tunnel:  [Error: ENOENT: no such file or directory, open 'C:\Users\Parisa-pc\AppData\Roaming\Outline\connection_store'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Parisa-pc\\AppData\\Roaming\\Outline\\connection_store'
}
Sentry Logger [log]: Deleted Crashpad metadata file C:\Users\Parisa-pc\AppData\Roaming\Outline\Crashpad\metadata
connecting to Outline Server ...
[tun2socks] - checking connectivity ...
CryptAcquireContext failed with error -2146893813, trying to create NEWKEYSETAssertion "CryptAcquireContext failed with error -2146893809" failed at line 70 in \\_\_\github.com\eycorsican\go-tun2socks@v1.16.11\core\c\custom\sys_arch.c
[tun2socks.exe - EXIT]: Exited with code 3
could not connect: a [Error]
    at t.ChildProcessHelper.b (C:\Program Files (x86)\Outline\resources\app.asar\output\client\electron\index.js:2:674688)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  exitCode: 3
}
Error occurred in handler for 'outline-ipc-start-proxying': a [Error]
    at t.ChildProcessHelper.b (C:\Program Files (x86)\Outline\resources\app.asar\output\client\electron\index.js:2:674688)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  exitCode: 3
}
disconnected from ...
[5108:1205/183127.283:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is

### Steps to reproduce

1- Open the application
2- trying to connect to my server

### Outline Version

1.14.0

### What operation system are you using?

Windows

### Operating System Version

Windows 11

**Comment by sbruens** [comment]
Thank you for reaching out! Please contact us through the application on the device where you’re experiencing this issue  – or at [support.getoutline.org](https://support.getoutline.org/) – and include the GitHub issue number so that we can better support your needs.

If you haven’t already, check out the Outline Support Site at [support.getoutline.org](https://support.getoutline.org/s/) for access to help articles and more.
