### ISSUE TITLE
Please support IPv6 on iOS

### ISSUE THREAD

**Issue by nirobcsilsol** [Jigsaw-Code/outline-apps#671]
On iOS, Outline is the only VPN app that can be installed in China. Other VPN apps are all banned by China government. However, we can only connect to IPv4 shadowsocks server through Outline, while most IPv4 IP addresses are banned by GFW(Great Firewall). If Outline does not support IPv6 addresses, it is being impossible to bypass the GFW in China.

**Comment by hebbet** [comment]
See #91

**Comment by sbruens** [comment]
This was finally added in #2132. It will be going out in the next release!
